apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cad-adapter.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  server.py: |
{{ .Files.Get "files/server.py" | indent 4 }}
