resource "aws_s3_bucket" "this" {
  for_each = local.bucket_purposes

  bucket        = "${local.name_prefix}-${each.value.suffix}-${data.aws_caller_identity.current.account_id}"
  force_destroy = var.s3_force_destroy

  tags = {
    Purpose = each.value.description
  }
}

resource "aws_s3_bucket_public_access_block" "this" {
  for_each = aws_s3_bucket.this

  bucket                  = each.value.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "this" {
  for_each = aws_s3_bucket.this

  bucket = each.value.id

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.main.arn
      sse_algorithm     = "aws:kms"
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_versioning" "this" {
  for_each = aws_s3_bucket.this

  bucket = each.value.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "logs_archive" {
  bucket = aws_s3_bucket.this["logs_archive"].id

  rule {
    id     = "retain-logs-then-expire"
    status = "Enabled"

    filter {
      prefix = ""
    }

    expiration {
      days = 400
    }

    noncurrent_version_expiration {
      noncurrent_days = 90
    }
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "uploads" {
  bucket = aws_s3_bucket.this["uploads"].id

  rule {
    id     = "expire-temporary-processing-artifacts"
    status = "Enabled"

    filter {
      prefix = "tmp/"
    }

    expiration {
      days = 30
    }
  }
}

# Browser-facing presigned uploads require CORS for the application origin.
resource "aws_s3_bucket_cors_configuration" "uploads" {
  bucket = aws_s3_bucket.this["uploads"].id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "PUT", "POST", "HEAD"]
    allowed_origins = concat([local.docsie_base_url], var.additional_cors_origins)
    expose_headers  = ["ETag", "x-amz-request-id"]
    max_age_seconds = 3000
  }
}

resource "aws_secretsmanager_secret" "s3_bucket_map" {
  name        = "${local.name_prefix}/managed/s3-buckets"
  description = "S3 bucket names generated by Terraform for Docsie configuration"
  kms_key_id  = aws_kms_key.main.arn
}

resource "aws_secretsmanager_secret_version" "s3_bucket_map" {
  secret_id = aws_secretsmanager_secret.s3_bucket_map.id
  secret_string = jsonencode({
    for key, bucket in aws_s3_bucket.this : key => bucket.bucket
  })
}
