# Application configuration secrets, generated by Terraform and stored in AWS
# Secrets Manager. The installer syncs these into the cluster as the
# `docsie-secret` Kubernetes secret via External Secrets Operator.
#
# Field gotchas encoded here:
#   - Redis auth tokens can contain URL-reserved characters; REDIS_URL /
#     CELERY_BROKER_URL MUST urlencode() the token or Celery/Django fail to
#     connect while plain redis-cli works.
#   - ElastiCache has transit encryption on, so URLs are rediss:// and the
#     application needs REDIS_USE_SSL=true.
#   - The Celery broker uses Redis DB 2, cache/sessions DB 0, so broker
#     traffic cannot collide with cache flushes.
#   - Durable secret changes belong HERE (or in Secrets Manager). Direct
#     `kubectl edit secret` changes are reverted by External Secrets on the
#     next reconcile.

resource "random_password" "django_secret_key" {
  length           = 64
  special          = true
  override_special = "!#$%&()*+,-.:;<=>?@[]^_{|}~"
}

resource "random_password" "django_admin_url" {
  length  = 24
  special = false
  upper   = false
}

resource "random_id" "field_encryption_key" {
  byte_length = 32
}

resource "random_password" "docsie_webhook_key" {
  length  = 48
  special = false
}

locals {
  docsie_internal_base_url = "http://docsie-web.${var.platform_namespace}.svc.cluster.local"

  redis_url_base = "rediss://:${urlencode(random_password.redis_auth_token.result)}@${aws_elasticache_replication_group.redis.primary_endpoint_address}:6379"

  database_url = "postgres://${var.postgres_master_username}:${random_password.postgres_master.result}@${aws_rds_cluster.postgres.endpoint}:5432/${var.postgres_database_name}"

  app_secret_names = toset([
    "docsie/django",
    "docsie/email",
    "docsie/oauth",
    "docsie/storage",
    "docsie/datastores",
  ])

  app_secret_values = {
    "docsie/django" = {
      DJANGO_SETTINGS_MODULE       = "config.settings.onprem"
      DJANGO_DEBUG                 = "false"
      DJANGO_SECRET_KEY            = random_password.django_secret_key.result
      DJANGO_ADMIN_URL             = "${random_password.django_admin_url.result}/"
      FIELD_ENCRYPTION_KEY         = "${random_id.field_encryption_key.b64_url}="
      DOMAIN                       = var.docsie_domain
      APP_BASE_URL                 = local.docsie_base_url
      BASE_URL                     = local.docsie_base_url
      REDIRECT_URL                 = local.docsie_base_url
      DOCSIE_BASE_URL              = local.docsie_base_url
      BILLING_BASE_URL             = local.docsie_base_url
      DJANGO_SESSION_COOKIE_DOMAIN = ""
      ADDITIONAL_ALLOWED_HOSTS     = "${var.docsie_domain},docsie-web,docsie-web.${var.platform_namespace}.svc,docsie-web.${var.platform_namespace}.svc.cluster.local,localhost,127.0.0.1"
      CSRF_TRUSTED_ORIGINS         = "${local.docsie_base_url},${local.docsie_internal_base_url},http://localhost,http://127.0.0.1"
      OTP_WEBAUTHN_RP_ID           = var.docsie_domain
      OTP_WEBAUTHN_ALLOWED_ORIGINS = local.docsie_base_url
      ENTERPRISE_MODE              = "true"
      ENTERPRISE_PLAN_SLUG         = "enterpriselite"
      ENTERPRISE_LOGIN_URL         = "/onboarding/v3/login/"
      DOCSIE_WEBHOOK_KEY           = random_password.docsie_webhook_key.result
      # Cloud-SaaS side effects that do not apply to a self-hosted install.
      MANAGER_CLOUD_INTEGRATIONS_ENABLED = "false"
      CUSTOM_DOMAINS_ENABLED             = "false"
      CLOUDFRONT_INVALIDATIONS_ENABLED   = "false"
      EXTERNAL_TELEMETRY_ENABLED         = "false"
      MARKETING_AUTOMATION_ENABLED       = "false"
      MARKETING_AUTOMATION_PROVIDER      = "disabled"
      DISABLE_BILLING_SIDE_EFFECTS       = "true"
      DISABLE_S3_SIDE_EFFECTS            = "false"
    }

    "docsie/email" = {
      DJANGO_EMAIL_BACKEND          = var.enable_ses_smtp ? "django.core.mail.backends.smtp.EmailBackend" : "django.core.mail.backends.console.EmailBackend"
      DJANGO_DEFAULT_FROM_EMAIL     = var.enable_ses_smtp ? var.ses_from_email : "no-reply@${var.docsie_domain}"
      DJANGO_SERVER_EMAIL           = var.enable_ses_smtp ? var.ses_from_email : "server@${var.docsie_domain}"
      DJANGO_EMAIL_SUBJECT_PREFIX   = "Docsie"
      DJANGO_EMAIL_HOST             = var.enable_ses_smtp ? "email-smtp.${var.aws_region}.amazonaws.com" : ""
      DJANGO_EMAIL_PORT             = var.enable_ses_smtp ? "587" : "25"
      DJANGO_EMAIL_HOST_USER        = var.enable_ses_smtp ? aws_iam_access_key.ses_smtp[0].id : ""
      DJANGO_EMAIL_HOST_PASSWORD    = var.enable_ses_smtp ? aws_iam_access_key.ses_smtp[0].ses_smtp_password_v4 : ""
      DJANGO_EMAIL_USE_TLS          = var.enable_ses_smtp ? "true" : "false"
      DJANGO_EMAIL_USE_SSL          = "false"
      DJANGO_EMAIL_TIMEOUT          = "10"
      MAIL_FORCE_DEFAULT_FROM_EMAIL = var.enable_ses_smtp ? "true" : "false"
    }

    # S3 storage config. Access keys stay empty: pods use IRSA credentials.
    "docsie/storage" = {
      DOCSIE_USE_S3_STORAGE                  = "true"
      AWS_REGION                             = var.aws_region
      AWS_DEFAULT_REGION                     = var.aws_region
      DJANGO_AWS_ACCESS_KEY_ID               = ""
      DJANGO_AWS_SECRET_ACCESS_KEY           = ""
      DJANGO_AWS_S3_ENDPOINT_URL             = ""
      DJANGO_AWS_S3_PUBLIC_ENDPOINT_URL      = ""
      DJANGO_AWS_S3_REGION_NAME              = var.aws_region
      DJANGO_AWS_S3_ADDRESSING_STYLE         = "virtual"
      DJANGO_AWS_S3_SIGNATURE_VERSION        = "s3v4"
      DJANGO_AWS_QUERYSTRING_AUTH            = "true"
      PRESIGNED_UPLOAD_USE_ACL               = "false"
      DJANGO_AWS_STORAGE_BUCKET_NAME         = aws_s3_bucket.this["app_storage"].bucket
      DJANGO_AWS_UPLOAD_BUCKET_NAME          = aws_s3_bucket.this["uploads"].bucket
      DJANGO_AWS_IMAGE_CONVERTER_BUCKET_NAME = aws_s3_bucket.this["uploads"].bucket
      DJANGO_AWS_SWAGGER_BUCKET_NAME         = aws_s3_bucket.this["app_storage"].bucket
      DJANGO_AWS_TEMP_BUCKET_NAME            = aws_s3_bucket.this["uploads"].bucket
      DJANGO_AWS_FEEDBACK_BUCKET_NAME        = aws_s3_bucket.this["feedback"].bucket
      DJANGO_AWS_PORTAL_BUCKET_NAME          = aws_s3_bucket.this["portal"].bucket
      DOCSIE_CDN_BUCKET_NAME                 = aws_s3_bucket.this["app_storage"].bucket
    }

    # Composed datastore URLs. See file header for the urlencode()/rediss
    # gotchas — do not "simplify" these.
    "docsie/datastores" = {
      DATABASE_URL          = local.database_url
      POSTGRES_HOST         = aws_rds_cluster.postgres.endpoint
      POSTGRES_PORT         = "5432"
      POSTGRES_DB           = var.postgres_database_name
      POSTGRES_USER         = var.postgres_master_username
      POSTGRES_PASSWORD     = random_password.postgres_master.result
      CELERY_RESULT_BACKEND = "${local.redis_url_base}/2"
      REDIS_ENDPOINT        = aws_elasticache_replication_group.redis.primary_endpoint_address
      REDIS_HOST            = aws_elasticache_replication_group.redis.primary_endpoint_address
      REDIS_PORT            = "6379"
      REDIS_PASSWORD        = random_password.redis_auth_token.result
      REDIS_USE_SSL         = "true"
      REDIS_URL             = "${local.redis_url_base}/0"
      CELERY_BROKER_URL     = "${local.redis_url_base}/2"
    }
  }
}

resource "aws_secretsmanager_secret" "app" {
  for_each = local.app_secret_names

  name        = "${local.name_prefix}/${each.key}"
  description = "Application configuration for ${each.key}, generated by Terraform."
  kms_key_id  = aws_kms_key.main.arn

  recovery_window_in_days = 30
}

resource "aws_secretsmanager_secret_version" "app" {
  for_each = local.app_secret_values

  secret_id     = aws_secretsmanager_secret.app[each.key].id
  secret_string = jsonencode(each.value)
}

# SSO/OAuth credentials are customer-supplied. This secret is created with
# empty placeholders once; fill the real values directly in Secrets Manager.
# ignore_changes protects your edits from being clobbered on re-apply.
resource "aws_secretsmanager_secret_version" "oauth" {
  secret_id = aws_secretsmanager_secret.app["docsie/oauth"].id
  secret_string = jsonencode({
    GOOGLE_CLIENT_ID        = ""
    GOOGLE_CLIENT_SECRET    = ""
    MICROSOFT_CLIENT_ID     = ""
    MICROSOFT_CLIENT_SECRET = ""
    LINKEDIN_CLIENT_ID      = ""
    LINKEDIN_CLIENT_SECRET  = ""
    GITHUB_SECRET           = ""
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}
