{{- if eq .Values.global.secretProvider "doppler" }}
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-docsie-{{ .Values.doppler.config }}
  labels:
    {{- include "docsie.labels" . | nindent 4 }}
spec:
  host: https://api.doppler.com
  tokenSecret:
    name: {{ .Values.doppler.tokenSecretName }}
  managedSecret:
    name: {{ .Values.doppler.managedSecretName }}
    namespace: {{ .Release.Namespace }}
    type: Opaque
  resyncSeconds: {{ .Values.doppler.resyncSeconds }}
  verifyTLS: true
{{- end }}
